#ifndef GAMES_H
#define GAMES_H 1

#include <stdint.h>

enum game_t : uint8_t
{
    GAME_FINALB = 0,
    GAME_DONDOKOD,
    GAME_MEGAB,
    GAME_THUNDFOX,
    GAME_CAMELTRY,
    GAME_QTORIMON,
    GAME_LIQUIDK,
    GAME_QUIZHQ,
    GAME_SSI,
    GAME_GUNFRONT,
    GAME_GROWL,
    GAME_MJNQUEST,
    GAME_FOOTCHMP,
    GAME_KOSHIEN,
    GAME_YUYUGOGO,
    GAME_NINJAK,
    GAME_SOLFIGTR,
    GAME_QZQUEST,
    GAME_PULIRULA,
    GAME_METALB,
    GAME_QZCHIKYU,
    GAME_YESNOJ,
    GAME_DEADCONX,
    GAME_DINOREX,
    GAME_QJINSEI,
    GAME_QCRAYON,
    GAME_QCRAYON2,
    GAME_DRIFTOUT
};


#endif // GAMES_H
